package com.sunrise.dentalclinic.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * The core entity of the system. Maps directly onto brief section 2:
 * "Register New Appointment" - appointment number, patient name, address, contact number,
 * dentist name, treatment type, appointment date and time.
 *
 * Patient details are embedded directly here rather than in a separate Patient entity.
 * ASSUMPTION (document this in your report): the brief describes booking a "patient visit",
 * and does not require tracking a patient's full history across multiple visits, so a
 * simpler embedded model was chosen over a normalized Patient/Appointment relationship.
 * If you want extra marks for "more sophisticated data representation" (see the Design
 * Patterns/Architecture marking row), you could instead split this into a separate
 * Patient entity with a one-to-many relationship to Appointment - I can show you that
 * version too if you want to aim for the "Excellent" band.
 */
@Entity
@Table(name = "appointment")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Appointment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String appointmentNumber; // e.g. "APT-2026-0001", generated by the service layer

    @Column(nullable = false)
    private String patientName;

    @Column(nullable = false)
    private String address;

    @Column(nullable = false)
    private String contactNumber;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "dentist_id", nullable = false)
    private Dentist dentist;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "treatment_id", nullable = false)
    private Treatment treatment;

    @Column(nullable = false)
    private LocalDate appointmentDate;

    @Column(nullable = false)
    private LocalTime appointmentTime;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Status status = Status.SCHEDULED;

    public enum Status {
        SCHEDULED,
        COMPLETED,
        CANCELLED
    }
}
