name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend # <-- ඔයාගේ Backend folder එකේ exact නම මෙතනට දාන්න (උදා: Backend හෝ backend)

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: mvn -B test
